import { useEffect, useState } from 'react';
import { BookOpenCheck, Clock, GraduationCap, Layers3, Plus, UserPlus } from 'lucide-react';
import api from '../lib/api';
import Modal from '../components/Modal';
import { useAuth } from '../context/AuthContext';

const emptyCourse={title:'',slug:'',description:'',category:'Sales',level:'Beginner',published:true};
const emptyLesson={title:'',content:'',position:1,duration:10,videoUrl:''};

export default function Learning(){
  const {isAdmin,user}=useAuth();
  const [courses,setCourses]=useState([]);const [enrollments,setEnrollments]=useState([]);const [users,setUsers]=useState([]);
  const [courseOpen,setCourseOpen]=useState(false);const [enrollOpen,setEnrollOpen]=useState(false);const [lessonOpen,setLessonOpen]=useState(false);
  const [form,setForm]=useState(emptyCourse);const [enrollForm,setEnrollForm]=useState({userId:'',courseId:''});const [lessonForm,setLessonForm]=useState(emptyLesson);const [lessonCourse,setLessonCourse]=useState(null);
  const load=async()=>{const calls=[api.get('/courses'),api.get('/enrollments')];if(isAdmin)calls.push(api.get('/users'));const results=await Promise.all(calls);setCourses(results[0].data.courses);setEnrollments(results[1].data.enrollments);if(results[2])setUsers(results[2].data.users)};
  useEffect(()=>{load()},[]);
  const saveCourse=async(e)=>{e.preventDefault();await api.post('/courses',form);setForm(emptyCourse);setCourseOpen(false);load()};
  const enroll=async(e)=>{e.preventDefault();await api.post('/enrollments',enrollForm);setEnrollOpen(false);load()};
  const addLesson=async(e)=>{e.preventDefault();await api.post(`/courses/${lessonCourse.id}/lessons`,lessonForm);setLessonOpen(false);setLessonForm(emptyLesson);load()};
  const progress=async(id,value)=>{await api.patch(`/enrollments/${id}/progress`,{progress:Number(value)});load()};
  const enrollmentFor=(courseId)=>enrollments.find(e=>e.course.id===courseId&&(user.role==='SALES'||e.user.id===user.id));
  const openEnrollment=()=>{setEnrollForm({userId:users.find(u=>u.role==='SALES')?.id||users[0]?.id||'',courseId:courses[0]?.id||''});setEnrollOpen(true)};
  return <div className="page-stack">
    <section className="learning-hero"><div><span className="hero-pill"><GraduationCap size={15}/> Nexus Learning</span><h2>Build better teams inside the same revenue workspace.</h2><p>Training, enablement and progress tracking are integrated directly into the CRM.</p></div>{isAdmin&&<div className="hero-actions"><button className="secondary light-btn" onClick={openEnrollment}><UserPlus size={17}/> Enroll learner</button><button className="primary light-btn" onClick={()=>setCourseOpen(true)}><Plus size={17}/> Create course</button></div>}</section>
    <div className="section-title"><div><p className="eyebrow">Course catalog</p><h3>{isAdmin?'Manage learning content':'Your learning'}</h3></div></div>
    <div className="course-grid">{courses.map((c,i)=>{const en=enrollmentFor(c.id);return <article className="course-card" key={c.id}><div className={`course-cover cover-${(i%3)+1}`}><BookOpenCheck size={28}/><span>{c.category}</span></div><div className="course-body"><div className="course-tags"><span>{c.level}</span><span>{c.lessons.length} lessons</span>{!c.published&&<span className="draft">Draft</span>}</div><h3>{c.title}</h3><p>{c.description}</p><div className="course-foot"><span><Clock size={14}/>{c.lessons.reduce((a,l)=>a+l.duration,0)} min</span><span><Layers3 size={14}/>{c.enrollmentCount} learners</span></div>{isAdmin&&<button className="secondary wide course-action" onClick={()=>{setLessonCourse(c);setLessonForm({...emptyLesson,position:c.lessons.length+1});setLessonOpen(true)}}><Plus size={14}/> Add lesson</button>}{en&&<div className="learning-progress"><div><span>Your progress</span><strong>{en.progress}%</strong></div><input type="range" min="0" max="100" step="25" value={en.progress} onChange={e=>progress(en.id,e.target.value)}/></div>}</div></article>})}</div>
    {isAdmin&&enrollments.length>0&&<div className="panel"><div className="panel-head"><div><p className="eyebrow">Enrollment overview</p><h3>Learner progress</h3></div></div><div className="table-wrap"><table><thead><tr><th>Learner</th><th>Course</th><th>Progress</th><th>Status</th></tr></thead><tbody>{enrollments.map(e=><tr key={e.id}><td><strong>{e.user.name}</strong><span>{e.user.email}</span></td><td>{e.course.title}</td><td><div className="inline-progress"><i style={{width:`${e.progress}%`}}/></div><small>{e.progress}%</small></td><td><span className="badge">{e.status}</span></td></tr>)}</tbody></table></div></div>}
    <Modal open={courseOpen} title="Create course" onClose={()=>setCourseOpen(false)}><form className="form-grid" onSubmit={saveCourse}><label className="span-2">Course title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')})}/></label><label className="span-2">Slug<input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label className="span-2">Description<textarea rows="4" required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Level<select value={form.level} onChange={e=>setForm({...form,level:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label className="check-label span-2"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Publish course immediately</label><div className="modal-actions span-2"><button type="button" className="secondary" onClick={()=>setCourseOpen(false)}>Cancel</button><button className="primary">Create course</button></div></form></Modal>
    <Modal open={enrollOpen} title="Enroll a learner" onClose={()=>setEnrollOpen(false)}><form className="form-grid" onSubmit={enroll}><label className="span-2">User<select required value={enrollForm.userId} onChange={e=>setEnrollForm({...enrollForm,userId:e.target.value})}>{users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</select></label><label className="span-2">Course<select required value={enrollForm.courseId} onChange={e=>setEnrollForm({...enrollForm,courseId:e.target.value})}>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><div className="modal-actions span-2"><button type="button" className="secondary" onClick={()=>setEnrollOpen(false)}>Cancel</button><button className="primary">Enroll user</button></div></form></Modal>
    <Modal open={lessonOpen} title={`Add lesson${lessonCourse?` · ${lessonCourse.title}`:''}`} onClose={()=>setLessonOpen(false)}><form className="form-grid" onSubmit={addLesson}><label className="span-2">Lesson title<input required value={lessonForm.title} onChange={e=>setLessonForm({...lessonForm,title:e.target.value})}/></label><label className="span-2">Lesson content<textarea rows="5" required value={lessonForm.content} onChange={e=>setLessonForm({...lessonForm,content:e.target.value})}/></label><label>Position<input type="number" min="1" required value={lessonForm.position} onChange={e=>setLessonForm({...lessonForm,position:Number(e.target.value)})}/></label><label>Duration (minutes)<input type="number" min="1" required value={lessonForm.duration} onChange={e=>setLessonForm({...lessonForm,duration:Number(e.target.value)})}/></label><label className="span-2">Video URL (optional)<input type="url" value={lessonForm.videoUrl} onChange={e=>setLessonForm({...lessonForm,videoUrl:e.target.value})}/></label><div className="modal-actions span-2"><button type="button" className="secondary" onClick={()=>setLessonOpen(false)}>Cancel</button><button className="primary">Add lesson</button></div></form></Modal>
  </div>
}
