import { useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpenCheck, BriefcaseBusiness, ShieldCheck, Sparkles } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export default function Login(){
  const {user,login}=useAuth();const navigate=useNavigate();const [email,setEmail]=useState('superadmin@nexus.dev');const [password,setPassword]=useState('Password@123');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  if(user)return <Navigate to="/" replace/>;
  const submit=async(e)=>{e.preventDefault();setLoading(true);setError('');try{await login(email,password);navigate('/')}catch(err){setError(err.response?.data?.message||'Login failed')}finally{setLoading(false)}};
  const accounts=[['SuperAdmin','superadmin@nexus.dev'],['Admin','admin@nexus.dev'],['Sales','sales@nexus.dev']];
  return <div className="login-page"><section className="login-showcase"><div className="showcase-inner"><div className="brand light"><div className="brand-mark"><Sparkles size={18}/></div><div><strong>Nexus</strong><span>CRM + LMS</span></div></div><div className="hero-copy"><span className="hero-pill">Portfolio-ready revenue workspace</span><h1>One modern workspace for customer growth and team learning.</h1><p>Manage leads, pipeline, contacts, tasks, team permissions, training courses and learning progress without switching products.</p></div><div className="feature-grid"><div><BriefcaseBusiness/><strong>CRM pipeline</strong><span>Track revenue from lead to won deal.</span></div><div><BookOpenCheck/><strong>Built-in LMS</strong><span>Enable onboarding and sales learning.</span></div><div><ShieldCheck/><strong>Role based</strong><span>SuperAdmin, Admin and Sales access.</span></div></div></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><p className="eyebrow">Welcome back</p><h2>Sign in to Nexus</h2><p className="muted">Use a seeded demo account or your own account.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error-box">{error}</div>}<button className="primary wide" disabled={loading}>{loading?'Signing in...':'Sign in'} <ArrowRight size={17}/></button><div className="demo-accounts"><span>Demo accounts · password <b>Password@123</b></span>{accounts.map(([role,mail])=><button type="button" key={mail} onClick={()=>{setEmail(mail);setPassword('Password@123')}}><strong>{role}</strong><span>{mail}</span></button>)}</div></form></section></div>
}
